const mongoose = require('mongoose');

const AuditSchema = new mongoose.Schema({
    nom: { type: String },
    emailc: { type: String },
    numt: { type: Number },
    rssi: { type: String },
    emailr: { type: String },
    auditor: { type: String },
    norme: { type: String },
    date: { type: Date, required:true },

    // Partie 1
    at1: { type: Boolean, default: false },
    at2: { type: String, default: "There's no recommendation for that" },
    at3: { type: Boolean, default: false },
    at4: { type: String, default: "There's no recommendation for that" },
    at5: { type: Boolean, default: false },
    at6: { type: String, default: "There's no recommendation for that" },

    // Partie 2 ORGANIZATION
    at7: { type: Boolean, default: false },
    at8: { type: String, default: "There's no recommendation for that" },
    at9: { type: Boolean, default: false },
    at10: { type: String, default: "There's no recommendation for that" },
    at11: { type: Boolean, default: false },
    at12: { type: String, default: "There's no recommendation for that" },
    at13: { type: Boolean, default: false },
    at14: { type: String, default: "There's no recommendation for that" },
    at15: { type: Boolean, default: false },
    at16: { type: String, default: "There's no recommendation for that" },
    at17: { type: Boolean, default: false },
    at18: { type: String, default: "There's no recommendation for that" },
    at19: { type: Boolean, default: false },
    at20: { type: String, default: "There's no recommendation for that" },

    // Partie 3 HR
    at21: { type: Boolean, default: false },
    at22: { type: String, default: "There's no recommendation for that" },
    at23: { type: Boolean, default: false },
    at24: { type: String, default: "There's no recommendation for that" },
    at25: { type: Boolean, default: false },
    at26: { type: String, default: "There's no recommendation for that" },
    at27: { type: Boolean, default: false },
    at28: { type: String, default: "There's no recommendation for that" },
    at29: { type: Boolean, default: false },
    at30: { type: String, default: "There's no recommendation for that" },
    at31: { type: Boolean, default: false },
    at32: { type: String, default: "There's no recommendation for that" },

    // ASSET
    at33: { type: Boolean, default: false },
    at34: { type: String, default: "There's no recommendation for that" },
    at35: { type: Boolean, default: false },
    at36: { type: String, default: "There's no recommendation for that" },
    at37: { type: Boolean, default: false },
    at38: { type: String, default: "There's no recommendation for that" },
    at39: { type: Boolean, default: false },
    at40: { type: String, default: "There's no recommendation for that" },
    at41: { type: Boolean, default: false },
    at42: { type: String, default: "There's no recommendation for that" },
    at43: { type: Boolean, default: false },
    at44: { type: String, default: "There's no recommendation for that" },
    at45: { type: Boolean, default: false },
    at46: { type: String, default: "There's no recommendation for that" },
    at47: { type: Boolean, default: false },
    at48: { type: String, default: "There's no recommendation for that" },
    at49: { type: Boolean, default: false },
    at50: { type: String, default: "There's no recommendation for that" },
    at51: { type: Boolean, default: false },
    at52: { type: String, default: "There's no recommendation for that" },

    // ACCESS
    at53: { type: Boolean, default: false },
    at54: { type: String, default: "There's no recommendation for that" },
    at55: { type: Boolean, default: false },
    at56: { type: String, default: "There's no recommendation for that" },
    at57: { type: Boolean, default: false },
    at58: { type: String, default: "There's no recommendation for that" },
    at59: { type: Boolean, default: false },
    at60: { type: String, default: "There's no recommendation for that" },
    at61: { type: Boolean, default: false },
    at62: { type: String, default: "There's no recommendation for that" },
    at63: { type: Boolean, default: false },
    at64: { type: String, default: "There's no recommendation for that" },
    at65: { type: Boolean, default: false },
    at66: { type: String, default: "There's no recommendation for that" },
    at67: { type: Boolean, default: false },
    at68: { type: String, default: "There's no recommendation for that" },
    at69: { type: Boolean, default: false },
    at70: { type: String, default: "There's no recommendation for that" },
    at71: { type: Boolean, default: false },
    at72: { type: String, default: "There's no recommendation for that" },
    at73: { type: Boolean, default: false },
    at74: { type: String, default: "There's no recommendation for that" },
    at75: { type: Boolean, default: false },
    at76: { type: String, default: "There's no recommendation for that" },
    at77: { type: Boolean, default: false },
    at78: { type: String, default: "There's no recommendation for that" },
    at79: { type: Boolean, default: false },
    at80: { type: String, default: "There's no recommendation for that" },

    // CRYPTOGRAPHY
    at81: { type: Boolean, default: false },
    at82: { type: String, default: "There's no recommendation for that" },
    at83: { type: Boolean, default: false },
    at84: { type: String, default: "There's no recommendation for that" },

    // AREA
    at85: { type: Boolean, default: false },
    at86: { type: String, default: "There's no recommendation for that" },
    at87: { type: Boolean, default: false },
    at88: { type: String, default: "There's no recommendation for that" },
    at89: { type: Boolean, default: false },
    at90: { type: String, default: "There's no recommendation for that" },
    at91: { type: Boolean, default: false },
    at92: { type: String, default: "There's no recommendation for that" },
    at93: { type: Boolean, default: false },
    at94: { type: String, default: "There's no recommendation for that" },
    at95: { type: Boolean, default: false },
    at96: { type: String, default: "There's no recommendation for that" },
    at97: { type: Boolean, default: false },
    at98: { type: String, default: "There's no recommendation for that" },
    at99: { type: Boolean, default: false },
    at100: { type: String, default: "There's no recommendation for that" },
    at101: { type: Boolean, default: false },
    at102: { type: String, default: "There's no recommendation for that" },
    at103: { type: Boolean, default: false },
    at104: { type: String, default: "There's no recommendation for that" },
    at105: { type: Boolean, default: false },
    at106: { type: String, default: "There's no recommendation for that" },
    at107: { type: Boolean, default: false },
    at108: { type: String, default: "There's no recommendation for that" },
    at109: { type: Boolean, default: false },
    at110: { type: String, default: "There's no recommendation for that" },
    at111: { type: Boolean, default: false },
    at112: { type: String, default: "There's no recommendation for that" },
    at113: { type: Boolean, default: false },
    at114: { type: String, default: "There's no recommendation for that" },

    // OPERATION
    at115: { type: Boolean, default: false },
    at116: { type: String, default: "There's no recommendation for that" },
    at117: { type: Boolean, default: false },
    at118: { type: String, default: "There's no recommendation for that" },
    at119: { type: Boolean, default: false },
    at120: { type: String, default: "There's no recommendation for that" },
    at121: { type: Boolean, default: false },
    at122: { type: String, default: "There's no recommendation for that" },
    at123: { type: Boolean, default: false },
    at124: { type: String, default: "There's no recommendation for that" },
    at125: { type: Boolean, default: false },
    at126: { type: String, default: "There's no recommendation for that" },
    at127: { type: Boolean, default: false },
    at128: { type: String, default: "There's no recommendation for that" },
    at129: { type: Boolean, default: false },
    at130: { type: String, default: "There's no recommendation for that" },
    at131: { type: Boolean, default: false },
    at132: { type: String, default: "There's no recommendation for that" },
    at133: { type: Boolean, default: false },
    at134: { type: String, default: "There's no recommendation for that" },
    at135: { type: Boolean, default: false },
    at136: { type: String, default: "There's no recommendation for that" },
    at137: { type: Boolean, default: false },
    at138: { type: String, default: "There's no recommendation for that" },
    at139: { type: Boolean, default: false },
    at140: { type: String, default: "There's no recommendation for that" },
    at141: { type: Boolean, default: false },
    at142: { type: String, default: "There's no recommendation for that" },
    at143: { type: Boolean, default: false },
    at144: { type: String, default: "There's no recommendation for that" },

    // PROTECTION
    at145: { type: Boolean, default: false },
    at146: { type: String, default: "There's no recommendation for that" },
    at147: { type: Boolean, default: false },
    at148: { type: String, default: "There's no recommendation for that" },
    at149: { type: Boolean, default: false },
    at150: { type: String, default: "There's no recommendation for that" },
    at151: { type: Boolean, default: false },
    at152: { type: String, default: "There's no recommendation for that" },
    at153: { type: Boolean, default: false },
    at154: { type: String, default: "There's no recommendation for that" },
    at155: { type: Boolean, default: false },
    at156: { type: String, default: "There's no recommendation for that" },
    at157: { type: Boolean, default: false },
    at158: { type: String, default: "There's no recommendation for that" },
    at159: { type: Boolean, default: false },
    at160: { type: String, default: "There's no recommendation for that" },

    // DEV
    at161: { type: Boolean, default: false },
    at162: { type: String, default: "There's no recommendation for that" },
    at163: { type: Boolean, default: false },
    at164: { type: String, default: "There's no recommendation for that" },
    at165: { type: Boolean, default: false },
    at166: { type: String, default: "There's no recommendation for that" },
    at167: { type: Boolean, default: false },
    at168: { type: String, default: "There's no recommendation for that" },

    // SUPPLIERS
    at169: { type: Boolean, default: false },
    at170: { type: String, default: "There's no recommendation for that" },

    // INCIDENT
    at171: { type: Boolean, default: false },
    at172: { type: String, default: "There's no recommendation for that" },

    // BUSINESS
    at173: { type: Boolean, default: false },
    at174: { type: String, default: "There's no recommendation for that" },
    at175: { type: Boolean, default: false },
    at176: { type: String, default: "There's no recommendation for that" },

    // COMPLIANCEq
    at177: { type: Boolean, default: false },
    at178: { type: String, default: "There's no recommendation for that" },
    at179: { type: Boolean, default: false },
    at180: { type: String, default: "There's no recommendation for that" },
    at181: { type: Boolean, default: false },
    at182: { type: String, default: "There's no recommendation for that" },
    at183: { type: Boolean, default: false },
    at184: { type: String, default: "There's no recommendation for that" },
    at185: { type: Boolean, default: false },
    at186: { type: String, default: "There's no recommendation for that" },
    at187: { type: Boolean, default: false },
    at188: { type: String, default: "There's no recommendation for that" },
    at189: { type: Boolean, default: false },
    at190: { type: String, default: "There's no recommendation for that" },

    user: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    company: { type: mongoose.Schema.Types.ObjectId, ref: 'Company' }
});

const Audit = mongoose.model('Audit', AuditSchema);

module.exports = Audit;
